version: '3.8'

services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "6443:443"
    depends_on:
      - ldap

  guacd:
    image: guacamole/guacd
    container_name: guacd
    ports:
      - "4822:4822"

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    environment:
      GUACAMOLE_HOME: /config
    volumes:
      - ./guac-config:/config
      - ./guac-config/extensions:/config/extensions
    ports:
      - "8080:8080"
    depends_on:
      - guacd
      - ldap

  linux-desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: linux-desktop
    ports:
      - "3389:3389"   # RDP
      - "5901:5901"   # VNC

  linux-server1:
    image: linuxserver/openssh-server
    container_name: linux-server1
    environment:
      USER_NAME: npauser
      USER_PASSWORD: secret
      PASSWORD_ACCESS: "true"
    ports:
      - "2222:2222"

  linux-server2:
    image: linuxserver/openssh-server
    container_name: linux-server2
    environment:
      USER_NAME: npauser
      USER_PASSWORD: secret
      PASSWORD_ACCESS: "true"
    ports:
      - "2223:2222"

