ldap-hostname: ldap
ldap-port: 389

ldap-user-base-dn: ou=Users,dc=example,dc=com
ldap-group-base-dn: ou=Groups,dc=example,dc=com
ldap-username-attribute: uid
ldap-group-name-attribute: cn
ldap-member-attribute: member
ldap-config-base-dn: ou=Guacamole,dc=example,dc=com

guacd-hostname: guacd
guacd-port: 4822
