ldap-hostname: ldap
ldap-port: 389
ldap-user-base-dn: ou=Users,dc=example,dc=com
ldap-group-base-dn: ou=Groups,dc=example,dc=com
ldap-username-attribute: uid
ldap-config-base-dn: ou=Guacamole,dc=example,dc=com

guacd-hostname: guacd
guacd-port: 4822
